name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Navigate into the correct directory containing package.json
      - name: Change directory to the project folder
        run: cd Bookingsystem/Bookingsystem

      # Step 3: Verify the current directory and check for package.json
      - name: Check directory contents
        run: |
          pwd  # Prints the current directory
          ls -al  # Lists all files in the directory

      # Step 4: Install dependencies and build the project
      - run: |
          cd Bookingsystem/Bookingsystem  # Ensure we're in the right directory
          npm ci
          npm run build

      # Step 5: Deploy to Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BOOKINGSYSTEM_757C2 }}
          channelId: live
          projectId: bookingsystem-757c2

