name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Change to the correct directory (Bookingsystem)
      - name: Change directory to Bookingsystem
        run: cd Bookingsystem && pwd && ls -al

      # Step 3: Install dependencies and build the app
      - name: Install dependencies and build
        run: |
          cd Bookingsystem
          npm ci
          npm run build

      # Step 4: Deploy to Firebase
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BOOKINGSYSTEM_757C2 }}
          channelId: live
          projectId: bookingsystem-757c2
