name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: List the full directory structure recursively (for debugging)
      - name: List directory structure recursively
        run: |
          echo "Current working directory:"
          pwd
          echo "Directory contents:"
          ls -R

      # Step 3: Change directory to the correct folder containing package.json
      - name: Change directory to the folder containing package.json
        run: |
          # Check current working directory
          cd Bookingsystem/Bookingsystem  # Try this again
          echo "Current working directory after cd:"
          pwd
          ls -al

      # Step 4: Install dependencies and build the project
      - run: |
          cd Bookingsystem/Bookingsystem
          npm ci
          npm run build

      # Step 5: Deploy to Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BOOKINGSYSTEM_757C2 }}
          channelId: live
          projectId: bookingsystem-757c2
