name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Check the directory structure
      - name: List directory contents
        run: |
          echo "Current working directory:"
          pwd  # Prints the current directory
          echo "Directory contents:"
          ls -al  # Lists files in the current directory

      # Step 3: Navigate to the directory containing package.json
      - name: Change directory to the correct folder
        run: |
          cd Bookingsystem/Bookingsystem  # Try to change directory to the correct path

      # Step 4: Verify that package.json exists
      - name: Check for package.json
        run: |
          ls -al  # List files to ensure package.json is found

      # Step 5: Install dependencies and build the project
      - run: |
          cd Bookingsystem/Bookingsystem  # Ensure we're in the right directory
          npm ci
          npm run build

      # Step 6: Deploy to Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BOOKINGSYSTEM_757C2 }}
          channelId: live
          projectId: bookingsystem-757c2
