name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Check the directory structure (for debugging)
      - name: List directory contents
        run: |
          echo "Current working directory:"
          pwd
          echo "Directory contents:"
          ls -al

      # Step 3: Navigate to the correct directory containing package.json
      - name: Change directory to the folder containing package.json
        run: |
          cd Bookingsystem/Bookingsystem
          echo "Current working directory after cd:"
          pwd  # Confirm we're in the correct directory
          ls -al  # Confirm package.json is present

      # Step 4: Install dependencies and build the project
      - run: |
          cd Bookingsystem/Bookingsystem  # Ensure we're in the correct folder
          npm ci
          npm run build

      # Step 5: Deploy to Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BOOKINGSYSTEM_757C2 }}
          channelId: live
          projectId: bookingsystem-757c2
