name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Install dependencies and build
      - name: Install dependencies and build
        run: |
          cd Bookingsystem  # Correct the cd path
          npm ci
          npm run build

      # Step 3: Deploy to Firebase, specify entryPoint to firebase.json location
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BOOKINGSYSTEM_757C2 }}
          channelId: live
          projectId: bookingsystem-757c2
          entryPoint: 'Bookingsystem/firebase.json'  # Specify the correct path to firebase.json
