name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Verify the directory structure
      - name: Verify directory structure and package.json location
        run: |
          echo "Current working directory:"
          pwd
          echo "Listing all files in the repository:"
          ls -R

      # Step 3: Install dependencies and build the project
      - name: Install dependencies and build
        run: |
          # Go into the correct directory before running npm commands
          cd Bookingsystem/Bookingsystem
          echo "Current working directory (after cd):"
          pwd
          echo "Listing contents after cd:"
          ls -al
          # Install dependencies and build
          npm ci
          npm run build

      # Step 4: Deploy to Firebase Hosting
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BOOKINGSYSTEM_757C2 }}
          channelId: live
          projectId: bookingsystem-757c2
