name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Verify the directory structure
      - name: Verify directory structure and package.json location
        run: |
          echo "Current working directory:"
          pwd
          echo "Listing all files in the repository:"
          ls -R

      # Step 3: Change to the correct directory where package.json is located
      - name: Change to correct directory and install dependencies
        run: |
          cd Bookingsystem/Bookingsystem  # Navigate to the correct subdirectory
          echo "Current directory after cd:"
          pwd
          ls -al
          echo "Installing dependencies"
          npm ci
          npm run build

      # Step 4: Deploy to Firebase Hosting
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BOOKINGSYSTEM_757C2 }}
          channelId: live
          projectId: bookingsystem-757c2
