name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Verify the directory structure and package.json location
      - name: Verify directory structure and package.json location
        run: |
          echo "Current working directory:"
          pwd
          echo "Listing all files in the repository:"
          ls -R
          echo "Listing files in the root directory:"
          ls -al

      # Step 3: Install dependencies
      - name: Install dependencies and build
        run: |
          echo "Current directory before cd:"
          pwd
          cd Bookingsystem  # Correct the cd path
          echo "Current directory after cd:"
          pwd
          ls -al
          echo "Installing dependencies"
          npm ci
          npm run build

      # Step 4: Deploy to Firebase
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BOOKINGSYSTEM_757C2 }}
          channelId: live
          projectId: bookingsystem-757c2
